# Chap.4 numpy套件(numeric python)

為什麼需要numpy?
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [2]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [4]:
#numpy套件的ndarray型態，提供element-wise的操作  //各別
import numpy as np
a=np.array([1,2,3,4,5]) #個別*3
print(a*3)

[ 3  6  9 12 15]


In [6]:
a=np.array([1,2,3,4,5])
print(type(a)) #型態
print(a.shape) #ndaary的形狀(個數)
print(a.dtype) #資料型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(6,)
int32
1


In [8]:
import numpy as np
z=np.zeros(6)   #0
print(z)
print(np.empty((2,4)))  #二維陣列
print(np.arange(10)) 

[0. 0. 0. 0. 0. 0.]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.33590898e-321 4.67296746e-307 1.69121095e-306]]
[0 1 2 3 4 5 6 7 8 9]


# ndarray的進階操作


In [9]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [10]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)]) #2維陣列
print(my_2d_array)
print(my_2d_array[1,:])     #第二列全部
print(my_2d_array[:,1])     #全部的 第二個
print(my_2d_array[1,1])     #第二列 第二個

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [11]:
my_array=np.arange(0,10)
print(my_array)
print(my_array.shape)  #形狀
my_2d_array=my_array.reshape(2,5)  #1*10  切割成 2*5
print(my_2d_array)
print((np.arange(0,100).reshape(10,10))) #1*100 切割成10*10

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# numpy的空值nan

In [14]:
b=np.array([56,8,19,14,np.nan])   #np.nan =空值
print(b)

[56.  8. 19. 14. nan]


# Chap 5 
## 函式(數)
## 傳統的寫法

In [16]:
import math
radius=eval(input('請輸入圓的半徑：')) #把輸入的字串變成數學計算型態
print("圓的面積為：",radius*radius*math.pi)

請輸入圓的半徑：1.5
圓的面積為： 7.0685834705770345


# 面積計算函式

In [1]:
import math
def circle_area(radius):
    area=radius*radius*math.pi
    return area

print(circle_area(1))

3.141592653589793


# Chap6
OS套件:用來處理文件與目錄，與檔案相關操作

In [2]:
import os
print(os.getcwd()) #顯示目前所在的工作目錄

C:\Users\Administrator


In [18]:
#顯示幕錄下的檔案
os.listdir('.')

['.conda',
 '.condarc',
 '.config',
 '.dotnet',
 '.eclipse',
 '.ipynb_checkpoints',
 '.ipython',
 '.p2',
 '.packettracer',
 '.templateengine',
 '.tooling',
 '.VirtualBox',
 '.vscode',
 '20210514.ipynb',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'Cisco Packet Tracer 6.1.1sv',
 'Cisco Packet Tracer 7.3.0',
 'Cisco Packet Tracer 7.3.1',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'Intel',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Oracle',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Templates

In [25]:
#新增目錄
os.makedirs("tttt")
os.listdir(".")

['.conda',
 '.condarc',
 '.config',
 '.dotnet',
 '.eclipse',
 '.ipynb_checkpoints',
 '.ipython',
 '.p2',
 '.packettracer',
 '.templateengine',
 '.tooling',
 '.VirtualBox',
 '.vscode',
 '20210514.ipynb',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'Cisco Packet Tracer 6.1.1sv',
 'Cisco Packet Tracer 7.3.0',
 'Cisco Packet Tracer 7.3.1',
 'Contacts',
 'Cookies',
 'd',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'Intel',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Oracle',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Tem

In [26]:
#移除目錄
os.rmdir("test")
os.listdir(".")

['.conda',
 '.condarc',
 '.config',
 '.dotnet',
 '.eclipse',
 '.ipynb_checkpoints',
 '.ipython',
 '.p2',
 '.packettracer',
 '.templateengine',
 '.tooling',
 '.VirtualBox',
 '.vscode',
 '20210514.ipynb',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'Cisco Packet Tracer 6.1.1sv',
 'Cisco Packet Tracer 7.3.0',
 'Cisco Packet Tracer 7.3.1',
 'Contacts',
 'Cookies',
 'd',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'Intel',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Oracle',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Tem

## 檔案處理
os套件有自己的檔案處理命令，而比較常用的是python內建的open
* w =可寫(預設建立檔案) 若檔案存在則會清除舊檔案
* w+ =可寫可讀(預設建立檔案) 若檔案存在則會清除舊檔案
* r = 可讀
* r+ =可寫可讀 但寫入資料指向開頭
* a =可寫不能讀 寫入資料指向尾端
* a+ =可寫可讀 寫入資料指向尾端
* b =轉為2進位文件
* ab+ =2進位文件的讀寫 寫入資料指向尾端

In [27]:
# 新增檔案
a=open("a.txt","w") #新增檔案
a.write("this is a test1")
a.write("this is a test2\n")
a.write("this is a test3\n")
a.close() #關閉檔案

## 檢查檔案是否存在

In [28]:
os.path.isfile("a.txt")

True

# 讀取檔案

In [29]:
a=open("a.txt","r")
print(a.readline())
print(a.readline())
print(a.readline()) #多餘的命令，檔案只有兩行
a.close()

this is a test1this is a test2

this is a test3




In [30]:
a=open("a.txt","r")
print(a.readlines()) #一次讀取多行，與a.read()命令相同
a.close()

['this is a test1this is a test2\n', 'this is a test3\n']


In [31]:
# 加上檔案是否存在的判斷
if os.path.isfile("a.txt"):
    a=open("a.txt","r")
    print(a.readlines())
    a.close()
else:
    print("檔案不存在")

['this is a test1this is a test2\n', 'this is a test3\n']


# Split函式

In [32]:
if os.path.isfile("a.txt"):
    a=open("a.txt","r")
    for line in a:
        fields=line.split(" ") #以空白為切割欄位
        print(fields)
    a.close()
else:
    print("檔案不存在")

['this', 'is', 'a', 'test1this', 'is', 'a', 'test2\n']
['this', 'is', 'a', 'test3\n']


# 附加檔案

In [43]:
a=open("a.txt","a")
a.write("this is test4\n")
a.close()

In [44]:
a=open("a.txt","r")
print(a.readlines())
a.close()


['this is a test5\n', 'is is a test2\n', 'this is a test3\n', 'this is test4\n', 'this is a test5\n', 'this is a test5\n', 'this is a test5\n', 'this is test4\n']


# 比較a與r+的不同
* a寫在檔案的結尾
* r+寫在檔案的開頭

In [47]:
a=open("a.txt","r+")
a.write("this is a test5\n")
print(a.readlines())
a.close()

['this is a test5\n', 'is is a test2\n', 'this is a test3\n', 'this is test4\n', 'this is a test5\n', 'this is a test5\n', 'this is a test5\n', 'this is test4\n', 'this is a test5\n']


In [50]:
a=open("a.txt","r")
print(a.readlines())
a.close()

['this is a test5\n', 'is is a test2\n', 'this is a test3\n', 'this is test4\n', 'this is a test5\n', 'this is a test5\n', 'this is a test5\n', 'this is test4\n', 'this is a test5\n', 'this is a test5\n']


# 刪除檔案

In [54]:
if os.path.isfile("a.txt"):
    os.remove("a.txt")
    print("檔案刪除成功")
else:
    print("找不到檔案")
print(os.path.isfile("a.txt"))

找不到檔案
False


# Cahp7 錯誤處理
try:

except:

else:

finaly:

In [56]:
a=10
b=20
try:
    if a<b:
        print(n)
except:
    print("錯誤產生")

錯誤產生


# 指定錯誤類別處理

In [58]:
a=10
b=20
try:
    if a<b:
        print(n)
except NameError as e:
    print("錯誤產生，錯誤原因：",e)
except ZeroDivisionErroe:
    print("除以0錯誤")

錯誤產生，錯誤原因： name 'n' is not defined


In [ ]:
a=10
b=20
try:
    if a>b: #改變比較條件 讓錯誤不發生
        print(n)
except: 
    print("錯誤發生")
else:
    print("沒有錯誤發生會執行的部分")
    

In [ ]:
a=10
b=20
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else:
    print("沒有錯誤發生")
finally:
    print("不管有沒有錯誤一定會執行的部分")